CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(100),
    EMAIL VARCHAR(100),
    TEL VARCHAR(20),
    STATUS VARCHAR(1), -- 'A' activo
    MONTO_MAX DECIMAL(10,2),
    MONTO_DISPONIBLE DECIMAL(10,2),
    MONTO_UTILIZADO DECIMAL(10,2)
);
-- Cliente con Fondos
INSERT INTO CLIENTE (NOMBRE, STATUS, MONTO_MAX, MONTO_DISPONIBLE, MONTO_UTILIZADO) 
VALUES ('Cliente Rico', 'A', 50000.00, 50000.00, 0.00);
-- Cliente Sin Fondos (Para pruebas futuras)
INSERT INTO CLIENTE (NOMBRE, STATUS, MONTO_MAX, MONTO_DISPONIBLE, MONTO_UTILIZADO) 
VALUES ('Cliente Pobre', 'A', 100.00, 0.00, 100.00);

CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOMBRE VARCHAR(100),
    STATUS VARCHAR(1)
);
INSERT INTO PROVEEDOR (NOMBRE, STATUS) VALUES ('Proveedor General', 'A');

CREATE TABLE OPERACION (
    ID_OPERACION INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_CLIENTE INT,
    ID_PROVEEDOR INT,
    MONTO DECIMAL(10,2),
    STATUS_OP VARCHAR(1),
    FECHA_OP TIMESTAMP,
    AUTORIZACION INT,
    FOLIO INT
);

CREATE SEQUENCE SEC_FOLIO_OPER
    START WITH 1000
    INCREMENT BY 1;