CREATE TABLE ENVIOS (
    ID_ENVIO INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_PEDIDO INT,
    ID_CLIENTE INT,
    FECHA_REGISTRO DATE,
    FECHA_ENTREGA DATE
);